In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/april28-may6_full.csv')

In [3]:
df.tail()

,Unnamed: 0,screen_name,username,tweet_id,timestamp,text,hashtags,likes,retweets,replies,sentiment_score,location
12904,12904,Angeloj,AJ Crawdaddy,1257889164411965440,2020-05-06 04:25:21,‚ÄúLive music‚Äù will survive! We will ROCK again...,"['covid19', 'flatteningthecurve', 'blues', 'bl...",0,0,0,0.332919,"Atlanta, GA"
12905,12905,queendior7,Tashia-Semaj,1257889828471013377,2020-05-06 04:28:00,The perks of having a sister that is a hairsty...,[],1,0,0,0.205556,"Warsaw, Poland"
12906,12906,4PocketzFull,DWA,1257889917335744512,2020-05-06 04:28:21,I‚Äôm A Rare Breed. They Not Supposed To Underst...,['CoronaVirus'],3,0,0,0.150000,"St Paul, MN"
12907,12907,adrlopez,Adrian Lopez,1257890170558390273,2020-05-06 04:29:21,Celebrating Cinco de Mayo on Taco Tuesday w...,[],1,0,1,0.075000,"Queens, NY"
12908,12908,pidybi,ùîìùî¶ùî¨ùî±ùîØ ùîáùî∂ùîüùî¶ùî¢ùî†,1257891112301330433,2020-05-06 04:33:06,#aljazeera #Trump to wind down...https://www.a...,"['aljazeera', 'Trump']",0,0,0,-0.155556,"Surat, India"

In [4]:
ny_index_list = []

for num in range(0,12909):
    if 'NY' in df['location'][num]:
        ny_index_list.append(num)
        
len(ny_index_list)

1305

In [5]:
tx_index_list = []

for num in range(0,12909):
    if 'TX' in df['location'][num]:
        tx_index_list.append(num)
        
len(tx_index_list)

427

In [6]:
ny_df = df.loc[ny_index_list,:]

In [7]:
ny_df['city'] = [item.split(',')[0] for item in ny_df['location']]

In [8]:
ny_df['state'] = [item.split(',')[1] for item in ny_df['location']]

In [9]:
tx_df = df.loc[tx_index_list,:]

In [10]:
tx_df['city'] = [item.split(',')[0] for item in tx_df['location']]
tx_df['state'] = [item.split(',')[1] for item in tx_df['location']]

In [11]:
tx_df.head()

,Unnamed: 0,screen_name,username,tweet_id,timestamp,text,hashtags,likes,retweets,replies,sentiment_score,location,city,state
30,30,all512tv,Austin Live & Local,1255008728711000065,2020-04-28 05:39:32,http://subscribe.all512.com¬† From Texas Standa...,"['atx', 'austin', 'all512']",0,0,0,0.128125,"Austin, TX",Austin,TX
82,82,joshWUa,joshWUa,1255022095626571776,2020-04-28 06:32:39,Here everyone he found the cure for your #covi...,"['covid19', 'coronavirus', 'donaldtrump', 'AMo...",0,0,0,-0.542857,"El Paso, TX",El Paso,TX
138,138,malele76,#indal_yam_botq üëóüë†üëûüõçüëùüëúüï∂,1255037758588026880,2020-04-28 07:34:53,Let's be warm with this colourful cotton Gucci...,"['indal_yam_botq', 'LockdownSA', 'covid19']",0,0,0,0.600000,"Houston, TX",Houston,TX
170,170,phonemarttech,PhoneMart,1255047959420403713,2020-04-28 08:15:25,INSTAGRAM COVID-19 CASH GIVE AWAY CONTINUES !!...,['phonemartgiveaway'],1,1,0,0.333333,"Austin, TX",Austin,TX
209,209,JakobEbert,"Jakob Ebert, BVK",1255057661013356544,2020-04-28 08:53:58,"COVID-19\n#investing #mood #memes @ Berlin, Ge...","['investing', 'mood', 'memes']",0,0,0,0.000000,"Dallas, TX",Dallas,TX

In [12]:
df = pd.read_csv('../data/tweets_and_covid.csv')

In [13]:
df.sort_values('city')

,screen_name,username,tweet_id,tweet_timestamp,text,hashtags,likes,retweets,replies,sentiment_score,state,city,date,cases,deaths
1610,nigeriatunes,Number 1 Agbero.,1257122286596845568,2020-05-04 01:38:03,"Cross River preparing for life after COVID-19,...",['Nigeriatunes'],0,1,0,0.000000,TX,Abilene,2020-05-04 00:00:00,33131,914
1580,WBOP,Victor Zimmerman,1256749752403836934,2020-05-03 00:57:44,Reminder! Gov. Baker announced that the state‚Äô...,"['cityofboston', 'wbop', 'curfew', 'stayhome',...",0,0,0,0.000000,TX,Addison,2020-05-03 00:00:00,32296,890
1317,BC_904,‚¨õ‚¨õ‚¨õ‚¨õ,1255169486669459462,2020-04-28 16:18:20,Dear #coronavirus #igers #dankmemes #dankvide...,"['coronavirus', 'igers', 'dankmemes', 'dankvid...",0,0,0,0.000000,TX,Aldine,2020-04-28 00:00:00,26865,738
1476,TimminsToday,TimminsToday.com,1256239086160867328,2020-05-01 15:08:32,Ontario reports 421 new cases of COVID-19 toda...,[],0,0,0,0.136364,TX,Allen,2020-05-01 00:00:00,30339,853
846,mostrecently,Johannes J√ºngst,1256955538178551808,2020-05-03 14:35:28,In between green and blue #frankfurtammain #fr...,"['frankfurtammain', 'frankfurt', 'badhomburg',...",0,0,0,-0.100000,NY,Amherst,2020-05-03 00:00:00,316446,19189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920,egbonlekan,Ibuoye Olalekan,1257093590649655297,2020-05-03 23:44:02,Sad but true. \nNow that the lockdown is eased...,['COVID„Éº19'],2,2,0,0.075000,NY,Yonkers,2020-05-03 00:00:00,316446,19189
957,PastorHThomas,Bishop H. Thomas,1257215541997076481,2020-05-04 07:48:37,The Promise Beyond The Pain (The Good Shepherd...,"['footagenotHD', 'StillanEncourgingWordfromGod...",0,0,0,0.700000,NY,Yonkers,2020-05-04 00:00:00,318984,19415
316,inkdbyaj,INKD BY AJ,1255694636728942592,2020-04-30 03:05:05,My thoughts on Covid 19 + too much time on my ...,['hairtattoo'],0,0,0,0.200000,NY,Yonkers,2020-04-30 00:00:00,304401,18321
610,IPARKMUSIC,OOBANG,1256419983900450817,2020-05-02 03:07:21,‚ÄúAction speaks louder than words...‚Äù #humanity...,"['humanityfirst', 'iparkmusic', 'oobang', 'cor...",0,0,0,0.100000,NY,Yorktown Heights,2020-05-02 00:00:00,313008,18909
784,TORsAdventures,TORsAdventures,1256720004818534400,2020-05-02 22:59:32,Where would you be spending your Saturday Aft...,"['COVID', 'keywest', 'florida', 'floridakeys',...",0,0,0,0.000000,NY,Yorktown Heights,2020-05-02 00:00:00,313008,18909